// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct AccountDetail: Codable {
    /// Is 2fa enabled
    public var isIs2faEnabled: Bool?
    public var isCommandPinSet: Bool?
    public var timezone: String?
    /// Email notifications
    public var isEmailNotifications: Bool?
    /// Required. 16 characters or fewer. Letters, digits and /./-/_ only.
    public var username: String
    /// Email address
    public var email: String?
    /// Units imperial
    public var isUnitsImperial: Bool?
    public var lastLogin: Date?

    public init(isIs2faEnabled: Bool? = nil, isCommandPinSet: Bool? = nil, timezone: String? = nil, isEmailNotifications: Bool? = nil, username: String, email: String? = nil, isUnitsImperial: Bool? = nil, lastLogin: Date? = nil) {
        self.isIs2faEnabled = isIs2faEnabled
        self.isCommandPinSet = isCommandPinSet
        self.timezone = timezone
        self.isEmailNotifications = isEmailNotifications
        self.username = username
        self.email = email
        self.isUnitsImperial = isUnitsImperial
        self.lastLogin = lastLogin
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.isIs2faEnabled = try values.decodeIfPresent(Bool.self, forKey: "is_2fa_enabled")
        self.isCommandPinSet = try values.decodeIfPresent(Bool.self, forKey: "is_command_pin_set")
        self.timezone = try values.decodeIfPresent(String.self, forKey: "timezone")
        self.isEmailNotifications = try values.decodeIfPresent(Bool.self, forKey: "email_notifications")
        self.username = try values.decode(String.self, forKey: "username")
        self.email = try values.decodeIfPresent(String.self, forKey: "email")
        self.isUnitsImperial = try values.decodeIfPresent(Bool.self, forKey: "units_imperial")
        self.lastLogin = try values.decodeIfPresent(Date.self, forKey: "last_login")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(isIs2faEnabled, forKey: "is_2fa_enabled")
        try values.encodeIfPresent(isCommandPinSet, forKey: "is_command_pin_set")
        try values.encodeIfPresent(timezone, forKey: "timezone")
        try values.encodeIfPresent(isEmailNotifications, forKey: "email_notifications")
        try values.encode(username, forKey: "username")
        try values.encodeIfPresent(email, forKey: "email")
        try values.encodeIfPresent(isUnitsImperial, forKey: "units_imperial")
        try values.encodeIfPresent(lastLogin, forKey: "last_login")
    }
}
