// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct AlertHistoryFull: Codable {
    public var id: Int?
    public var type: Int
    public var typeDisplay: String
    public var timestamp: Date?
    public var commandID: Int?
    public var additionalData: String?
    public var car: Car?

    public init(id: Int? = nil, type: Int, typeDisplay: String, timestamp: Date? = nil, commandID: Int? = nil, additionalData: String? = nil, car: Car? = nil) {
        self.id = id
        self.type = type
        self.typeDisplay = typeDisplay
        self.timestamp = timestamp
        self.commandID = commandID
        self.additionalData = additionalData
        self.car = car
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decodeIfPresent(Int.self, forKey: "id")
        self.type = try values.decode(Int.self, forKey: "type")
        self.typeDisplay = try values.decode(String.self, forKey: "type_display")
        self.timestamp = try values.decodeIfPresent(Date.self, forKey: "timestamp")
        self.commandID = try values.decodeIfPresent(Int.self, forKey: "command_id")
        self.additionalData = try values.decodeIfPresent(String.self, forKey: "additional_data")
        self.car = try values.decodeIfPresent(Car.self, forKey: "car")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(id, forKey: "id")
        try values.encode(type, forKey: "type")
        try values.encode(typeDisplay, forKey: "type_display")
        try values.encodeIfPresent(timestamp, forKey: "timestamp")
        try values.encodeIfPresent(commandID, forKey: "command_id")
        try values.encodeIfPresent(additionalData, forKey: "additional_data")
        try values.encodeIfPresent(car, forKey: "car")
    }
}
