// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct Car: Codable {
    public var id: Int?
    public var tcuConfiguration: TCUConfiguration
    public var location: LocationInfo
    public var evInfo: EVInfo
    public var vehHealth: VehicleHealthInfo?
    public var sendToCarLocationAll: [SendToCarLocation]
    public var sendToCarLocation: SendToCarLocation?
    public var routePlans: [RoutePlan]
    public var commandTypeDisplay: String
    public var commandResultDisplay: String
    public var timerCommands: [CommandTimerSetting]
    public var commandRequestTime: Date?
    public var lastConnection: Date?
    public var supportedCommands: [Int]?
    public var sensitiveCommands: [Int]?
    /// Command pin enforced
    public var isCommandPinEnforced: Bool?
    public var vin: String
    public var nickname: String?
    public var smsConfig: [String: AnyJSON]
    public var color: Color?
    public var vehicleCode1: Int?
    public var vehicleCode2: Int?
    public var vehicleCode3: Int?
    public var vehicleCode4: Int?
    public var tcuModel: String?
    public var tcuSerial: String?
    public var iccid: String?
    public var tcuVer: String?
    public var tcuUser: String?
    public var tcuPass: String?
    /// Disable auth
    public var isDisableAuth: Bool?
    public var periodicRefresh: Int?
    public var periodicRefreshRunning: Int?
    public var commandID: Int?
    public var commandResult: Int?
    /// Command requested
    public var isCommandRequested: Bool?
    public var commandPayload: [String: AnyJSON]?
    public var commandType: Int?
    public var carrier: String?
    public var signalLevel: Int?
    public var odometer: Int?
    public var naviVersion: String?
    public var mapVersion: String?
    public var tcuVersion: String?
    public var favoriteChannels: [String: AnyJSON]?
    public var customChannels: [String: AnyJSON]?
    public var hmacKey: String?
    public var tcuType: TcuType?
    public var owner: Int

    public enum Color: String, Codable, CaseIterable {
        case lCoulisred = "l_coulisred"
        case lDeepblue = "l_deepblue"
        case lForgedbronze = "l_forgedbronze"
        case lGunmetallic = "l_gunmetallic"
        case lPearlwhite = "l_pearlwhite"
        case l2Pearlwhite = "l2_pearlwhite"
        case l2Gunmetallic = "l2_gunmetallic"
        case l2Jadefrostmetallic = "l2_jadefrostmetallic"
        case l2Superblack = "l2_superblack"
        case l2Vividblue = "l2_vividblue"
        case lPlanetblue = "l_planetblue"
        case lSuperblack = "l_superblack"
        case env200White = "env200_white"
    }

    public enum TcuType: String, Codable, CaseIterable {
        case continental2012
        case ficosa2016
    }

    public init(id: Int? = nil, tcuConfiguration: TCUConfiguration, location: LocationInfo, evInfo: EVInfo, vehHealth: VehicleHealthInfo? = nil, sendToCarLocationAll: [SendToCarLocation], sendToCarLocation: SendToCarLocation? = nil, routePlans: [RoutePlan], commandTypeDisplay: String, commandResultDisplay: String, timerCommands: [CommandTimerSetting], commandRequestTime: Date? = nil, lastConnection: Date? = nil, supportedCommands: [Int]? = nil, sensitiveCommands: [Int]? = nil, isCommandPinEnforced: Bool? = nil, vin: String, nickname: String? = nil, smsConfig: [String: AnyJSON], color: Color? = nil, vehicleCode1: Int? = nil, vehicleCode2: Int? = nil, vehicleCode3: Int? = nil, vehicleCode4: Int? = nil, tcuModel: String? = nil, tcuSerial: String? = nil, iccid: String? = nil, tcuVer: String? = nil, tcuUser: String? = nil, tcuPass: String? = nil, isDisableAuth: Bool? = nil, periodicRefresh: Int? = nil, periodicRefreshRunning: Int? = nil, commandID: Int? = nil, commandResult: Int? = nil, isCommandRequested: Bool? = nil, commandPayload: [String: AnyJSON]? = nil, commandType: Int? = nil, carrier: String? = nil, signalLevel: Int? = nil, odometer: Int? = nil, naviVersion: String? = nil, mapVersion: String? = nil, tcuVersion: String? = nil, favoriteChannels: [String: AnyJSON]? = nil, customChannels: [String: AnyJSON]? = nil, hmacKey: String? = nil, tcuType: TcuType? = nil, owner: Int) {
        self.id = id
        self.tcuConfiguration = tcuConfiguration
        self.location = location
        self.evInfo = evInfo
        self.vehHealth = vehHealth
        self.sendToCarLocationAll = sendToCarLocationAll
        self.sendToCarLocation = sendToCarLocation
        self.routePlans = routePlans
        self.commandTypeDisplay = commandTypeDisplay
        self.commandResultDisplay = commandResultDisplay
        self.timerCommands = timerCommands
        self.commandRequestTime = commandRequestTime
        self.lastConnection = lastConnection
        self.supportedCommands = supportedCommands
        self.sensitiveCommands = sensitiveCommands
        self.isCommandPinEnforced = isCommandPinEnforced
        self.vin = vin
        self.nickname = nickname
        self.smsConfig = smsConfig
        self.color = color
        self.vehicleCode1 = vehicleCode1
        self.vehicleCode2 = vehicleCode2
        self.vehicleCode3 = vehicleCode3
        self.vehicleCode4 = vehicleCode4
        self.tcuModel = tcuModel
        self.tcuSerial = tcuSerial
        self.iccid = iccid
        self.tcuVer = tcuVer
        self.tcuUser = tcuUser
        self.tcuPass = tcuPass
        self.isDisableAuth = isDisableAuth
        self.periodicRefresh = periodicRefresh
        self.periodicRefreshRunning = periodicRefreshRunning
        self.commandID = commandID
        self.commandResult = commandResult
        self.isCommandRequested = isCommandRequested
        self.commandPayload = commandPayload
        self.commandType = commandType
        self.carrier = carrier
        self.signalLevel = signalLevel
        self.odometer = odometer
        self.naviVersion = naviVersion
        self.mapVersion = mapVersion
        self.tcuVersion = tcuVersion
        self.favoriteChannels = favoriteChannels
        self.customChannels = customChannels
        self.hmacKey = hmacKey
        self.tcuType = tcuType
        self.owner = owner
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decodeIfPresent(Int.self, forKey: "id")
        self.tcuConfiguration = try values.decode(TCUConfiguration.self, forKey: "tcu_configuration")
        self.location = try values.decode(LocationInfo.self, forKey: "location")
        self.evInfo = try values.decode(EVInfo.self, forKey: "ev_info")
        self.vehHealth = try values.decodeIfPresent(VehicleHealthInfo.self, forKey: "veh_health")
        self.sendToCarLocationAll = try values.decode([SendToCarLocation].self, forKey: "send_to_car_location_all")
        self.sendToCarLocation = try values.decodeIfPresent(SendToCarLocation.self, forKey: "send_to_car_location")
        self.routePlans = try values.decode([RoutePlan].self, forKey: "route_plans")
        self.commandTypeDisplay = try values.decode(String.self, forKey: "command_type_display")
        self.commandResultDisplay = try values.decode(String.self, forKey: "command_result_display")
        self.timerCommands = try values.decode([CommandTimerSetting].self, forKey: "timer_commands")
        self.commandRequestTime = try values.decodeIfPresent(Date.self, forKey: "command_request_time")
        self.lastConnection = try values.decodeIfPresent(Date.self, forKey: "last_connection")
        self.supportedCommands = try values.decodeIfPresent([Int].self, forKey: "supported_commands")
        self.sensitiveCommands = try values.decodeIfPresent([Int].self, forKey: "sensitive_commands")
        self.isCommandPinEnforced = try values.decodeIfPresent(Bool.self, forKey: "command_pin_enforced")
        self.vin = try values.decode(String.self, forKey: "vin")
        self.nickname = try values.decodeIfPresent(String.self, forKey: "nickname")
        self.smsConfig = try values.decode([String: AnyJSON].self, forKey: "sms_config")
        self.color = try values.decodeIfPresent(Color.self, forKey: "color")
        self.vehicleCode1 = try values.decodeIfPresent(Int.self, forKey: "vehicle_code1")
        self.vehicleCode2 = try values.decodeIfPresent(Int.self, forKey: "vehicle_code2")
        self.vehicleCode3 = try values.decodeIfPresent(Int.self, forKey: "vehicle_code3")
        self.vehicleCode4 = try values.decodeIfPresent(Int.self, forKey: "vehicle_code4")
        self.tcuModel = try values.decodeIfPresent(String.self, forKey: "tcu_model")
        self.tcuSerial = try values.decodeIfPresent(String.self, forKey: "tcu_serial")
        self.iccid = try values.decodeIfPresent(String.self, forKey: "iccid")
        self.tcuVer = try values.decodeIfPresent(String.self, forKey: "tcu_ver")
        self.tcuUser = try values.decodeIfPresent(String.self, forKey: "tcu_user")
        self.tcuPass = try values.decodeIfPresent(String.self, forKey: "tcu_pass")
        self.isDisableAuth = try values.decodeIfPresent(Bool.self, forKey: "disable_auth")
        self.periodicRefresh = try values.decodeIfPresent(Int.self, forKey: "periodic_refresh")
        self.periodicRefreshRunning = try values.decodeIfPresent(Int.self, forKey: "periodic_refresh_running")
        self.commandID = try values.decodeIfPresent(Int.self, forKey: "command_id")
        self.commandResult = try values.decodeIfPresent(Int.self, forKey: "command_result")
        self.isCommandRequested = try values.decodeIfPresent(Bool.self, forKey: "command_requested")
        self.commandPayload = try values.decodeIfPresent([String: AnyJSON].self, forKey: "command_payload")
        self.commandType = try values.decodeIfPresent(Int.self, forKey: "command_type")
        self.carrier = try values.decodeIfPresent(String.self, forKey: "carrier")
        self.signalLevel = try values.decodeIfPresent(Int.self, forKey: "signal_level")
        self.odometer = try values.decodeIfPresent(Int.self, forKey: "odometer")
        self.naviVersion = try values.decodeIfPresent(String.self, forKey: "navi_version")
        self.mapVersion = try values.decodeIfPresent(String.self, forKey: "map_version")
        self.tcuVersion = try values.decodeIfPresent(String.self, forKey: "tcu_version")
        self.favoriteChannels = try values.decodeIfPresent([String: AnyJSON].self, forKey: "favorite_channels")
        self.customChannels = try values.decodeIfPresent([String: AnyJSON].self, forKey: "custom_channels")
        self.hmacKey = try values.decodeIfPresent(String.self, forKey: "hmac_key")
        self.tcuType = try values.decodeIfPresent(TcuType.self, forKey: "tcu_type")
        self.owner = try values.decode(Int.self, forKey: "owner")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(id, forKey: "id")
        try values.encode(tcuConfiguration, forKey: "tcu_configuration")
        try values.encode(location, forKey: "location")
        try values.encode(evInfo, forKey: "ev_info")
        try values.encodeIfPresent(vehHealth, forKey: "veh_health")
        try values.encode(sendToCarLocationAll, forKey: "send_to_car_location_all")
        try values.encodeIfPresent(sendToCarLocation, forKey: "send_to_car_location")
        try values.encode(routePlans, forKey: "route_plans")
        try values.encode(commandTypeDisplay, forKey: "command_type_display")
        try values.encode(commandResultDisplay, forKey: "command_result_display")
        try values.encode(timerCommands, forKey: "timer_commands")
        try values.encodeIfPresent(commandRequestTime, forKey: "command_request_time")
        try values.encodeIfPresent(lastConnection, forKey: "last_connection")
        try values.encodeIfPresent(supportedCommands, forKey: "supported_commands")
        try values.encodeIfPresent(sensitiveCommands, forKey: "sensitive_commands")
        try values.encodeIfPresent(isCommandPinEnforced, forKey: "command_pin_enforced")
        try values.encode(vin, forKey: "vin")
        try values.encodeIfPresent(nickname, forKey: "nickname")
        try values.encode(smsConfig, forKey: "sms_config")
        try values.encodeIfPresent(color, forKey: "color")
        try values.encodeIfPresent(vehicleCode1, forKey: "vehicle_code1")
        try values.encodeIfPresent(vehicleCode2, forKey: "vehicle_code2")
        try values.encodeIfPresent(vehicleCode3, forKey: "vehicle_code3")
        try values.encodeIfPresent(vehicleCode4, forKey: "vehicle_code4")
        try values.encodeIfPresent(tcuModel, forKey: "tcu_model")
        try values.encodeIfPresent(tcuSerial, forKey: "tcu_serial")
        try values.encodeIfPresent(iccid, forKey: "iccid")
        try values.encodeIfPresent(tcuVer, forKey: "tcu_ver")
        try values.encodeIfPresent(tcuUser, forKey: "tcu_user")
        try values.encodeIfPresent(tcuPass, forKey: "tcu_pass")
        try values.encodeIfPresent(isDisableAuth, forKey: "disable_auth")
        try values.encodeIfPresent(periodicRefresh, forKey: "periodic_refresh")
        try values.encodeIfPresent(periodicRefreshRunning, forKey: "periodic_refresh_running")
        try values.encodeIfPresent(commandID, forKey: "command_id")
        try values.encodeIfPresent(commandResult, forKey: "command_result")
        try values.encodeIfPresent(isCommandRequested, forKey: "command_requested")
        try values.encodeIfPresent(commandPayload, forKey: "command_payload")
        try values.encodeIfPresent(commandType, forKey: "command_type")
        try values.encodeIfPresent(carrier, forKey: "carrier")
        try values.encodeIfPresent(signalLevel, forKey: "signal_level")
        try values.encodeIfPresent(odometer, forKey: "odometer")
        try values.encodeIfPresent(naviVersion, forKey: "navi_version")
        try values.encodeIfPresent(mapVersion, forKey: "map_version")
        try values.encodeIfPresent(tcuVersion, forKey: "tcu_version")
        try values.encodeIfPresent(favoriteChannels, forKey: "favorite_channels")
        try values.encodeIfPresent(customChannels, forKey: "custom_channels")
        try values.encodeIfPresent(hmacKey, forKey: "hmac_key")
        try values.encodeIfPresent(tcuType, forKey: "tcu_type")
        try values.encode(owner, forKey: "owner")
    }
}
