// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct CarSerializerList: Codable {
    public var vin: String
    public var lastConnection: Date?
    public var nickname: String?
    public var evInfo: EVInfo
    public var location: LocationInfo
    public var carrier: String?
    public var signalLevel: Int?
    public var tcuType: TcuType?

    public enum TcuType: String, Codable, CaseIterable {
        case continental2012
        case ficosa2016
    }

    public init(vin: String, lastConnection: Date? = nil, nickname: String? = nil, evInfo: EVInfo, location: LocationInfo, carrier: String? = nil, signalLevel: Int? = nil, tcuType: TcuType? = nil) {
        self.vin = vin
        self.lastConnection = lastConnection
        self.nickname = nickname
        self.evInfo = evInfo
        self.location = location
        self.carrier = carrier
        self.signalLevel = signalLevel
        self.tcuType = tcuType
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.vin = try values.decode(String.self, forKey: "vin")
        self.lastConnection = try values.decodeIfPresent(Date.self, forKey: "last_connection")
        self.nickname = try values.decodeIfPresent(String.self, forKey: "nickname")
        self.evInfo = try values.decode(EVInfo.self, forKey: "ev_info")
        self.location = try values.decode(LocationInfo.self, forKey: "location")
        self.carrier = try values.decodeIfPresent(String.self, forKey: "carrier")
        self.signalLevel = try values.decodeIfPresent(Int.self, forKey: "signal_level")
        self.tcuType = try values.decodeIfPresent(TcuType.self, forKey: "tcu_type")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(vin, forKey: "vin")
        try values.encodeIfPresent(lastConnection, forKey: "last_connection")
        try values.encodeIfPresent(nickname, forKey: "nickname")
        try values.encode(evInfo, forKey: "ev_info")
        try values.encode(location, forKey: "location")
        try values.encodeIfPresent(carrier, forKey: "carrier")
        try values.encodeIfPresent(signalLevel, forKey: "signal_level")
        try values.encodeIfPresent(tcuType, forKey: "tcu_type")
    }
}
