// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct CarUpdating: Codable {
    public var sendToCarLocation: SendToCarLocation?
    public var sendToCarLocationAll: [SendToCarLocation]?
    public var evInfo: EVInfoUpdating?
    public var routePlans: [RoutePlan]?
    public var favoriteChannels: [String: AnyJSON]?
    public var customChannels: [String: AnyJSON]?

    public init(sendToCarLocation: SendToCarLocation? = nil, sendToCarLocationAll: [SendToCarLocation]? = nil, evInfo: EVInfoUpdating? = nil, routePlans: [RoutePlan]? = nil, favoriteChannels: [String: AnyJSON]? = nil, customChannels: [String: AnyJSON]? = nil) {
        self.sendToCarLocation = sendToCarLocation
        self.sendToCarLocationAll = sendToCarLocationAll
        self.evInfo = evInfo
        self.routePlans = routePlans
        self.favoriteChannels = favoriteChannels
        self.customChannels = customChannels
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.sendToCarLocation = try values.decodeIfPresent(SendToCarLocation.self, forKey: "send_to_car_location")
        self.sendToCarLocationAll = try values.decodeIfPresent([SendToCarLocation].self, forKey: "send_to_car_location_all")
        self.evInfo = try values.decodeIfPresent(EVInfoUpdating.self, forKey: "ev_info")
        self.routePlans = try values.decodeIfPresent([RoutePlan].self, forKey: "route_plans")
        self.favoriteChannels = try values.decodeIfPresent([String: AnyJSON].self, forKey: "favorite_channels")
        self.customChannels = try values.decodeIfPresent([String: AnyJSON].self, forKey: "custom_channels")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(sendToCarLocation, forKey: "send_to_car_location")
        try values.encodeIfPresent(sendToCarLocationAll, forKey: "send_to_car_location_all")
        try values.encodeIfPresent(evInfo, forKey: "ev_info")
        try values.encodeIfPresent(routePlans, forKey: "route_plans")
        try values.encodeIfPresent(favoriteChannels, forKey: "favorite_channels")
        try values.encodeIfPresent(customChannels, forKey: "custom_channels")
    }
}
