// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct CommandTimerSetting: Codable {
    public var id: Int?
    public var commandTypeDisplay: String?
    public var lastCommandResultDisplay: String?
    public var timerTypeDisplay: String?
    public var lastCommandExecution: Date?
    /// Enabled
    public var isEnabled: Bool?
    public var name: String
    public var timerType: Int?
    public var commandType: Int?
    public var lastCommandResult: Int?
    /// Weekday mon
    public var isWeekdayMon: Bool?
    /// Weekday tue
    public var isWeekdayTue: Bool?
    /// Weekday wed
    public var isWeekdayWed: Bool?
    /// Weekday thu
    public var isWeekdayThu: Bool?
    /// Weekday fri
    public var isWeekdayFri: Bool?
    /// Weekday sat
    public var isWeekdaySat: Bool?
    /// Weekday sun
    public var isWeekdaySun: Bool?
    public var time: String
    public var date: NaiveDate?

    public init(id: Int? = nil, commandTypeDisplay: String? = nil, lastCommandResultDisplay: String? = nil, timerTypeDisplay: String? = nil, lastCommandExecution: Date? = nil, isEnabled: Bool? = nil, name: String, timerType: Int? = nil, commandType: Int? = nil, lastCommandResult: Int? = nil, isWeekdayMon: Bool? = nil, isWeekdayTue: Bool? = nil, isWeekdayWed: Bool? = nil, isWeekdayThu: Bool? = nil, isWeekdayFri: Bool? = nil, isWeekdaySat: Bool? = nil, isWeekdaySun: Bool? = nil, time: String, date: NaiveDate? = nil) {
        self.id = id
        self.commandTypeDisplay = commandTypeDisplay
        self.lastCommandResultDisplay = lastCommandResultDisplay
        self.timerTypeDisplay = timerTypeDisplay
        self.lastCommandExecution = lastCommandExecution
        self.isEnabled = isEnabled
        self.name = name
        self.timerType = timerType
        self.commandType = commandType
        self.lastCommandResult = lastCommandResult
        self.isWeekdayMon = isWeekdayMon
        self.isWeekdayTue = isWeekdayTue
        self.isWeekdayWed = isWeekdayWed
        self.isWeekdayThu = isWeekdayThu
        self.isWeekdayFri = isWeekdayFri
        self.isWeekdaySat = isWeekdaySat
        self.isWeekdaySun = isWeekdaySun
        self.time = time
        self.date = date
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decodeIfPresent(Int.self, forKey: "id")
        self.commandTypeDisplay = try values.decodeIfPresent(String.self, forKey: "command_type_display")
        self.lastCommandResultDisplay = try values.decodeIfPresent(String.self, forKey: "last_command_result_display")
        self.timerTypeDisplay = try values.decodeIfPresent(String.self, forKey: "timer_type_display")
        self.lastCommandExecution = try values.decodeIfPresent(Date.self, forKey: "last_command_execution")
        self.isEnabled = try values.decodeIfPresent(Bool.self, forKey: "enabled")
        self.name = try values.decode(String.self, forKey: "name")
        self.timerType = try values.decodeIfPresent(Int.self, forKey: "timer_type")
        self.commandType = try values.decodeIfPresent(Int.self, forKey: "command_type")
        self.lastCommandResult = try values.decodeIfPresent(Int.self, forKey: "last_command_result")
        self.isWeekdayMon = try values.decodeIfPresent(Bool.self, forKey: "weekday_mon")
        self.isWeekdayTue = try values.decodeIfPresent(Bool.self, forKey: "weekday_tue")
        self.isWeekdayWed = try values.decodeIfPresent(Bool.self, forKey: "weekday_wed")
        self.isWeekdayThu = try values.decodeIfPresent(Bool.self, forKey: "weekday_thu")
        self.isWeekdayFri = try values.decodeIfPresent(Bool.self, forKey: "weekday_fri")
        self.isWeekdaySat = try values.decodeIfPresent(Bool.self, forKey: "weekday_sat")
        self.isWeekdaySun = try values.decodeIfPresent(Bool.self, forKey: "weekday_sun")
        self.time = try values.decode(String.self, forKey: "time")
        self.date = try values.decodeIfPresent(NaiveDate.self, forKey: "date")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(id, forKey: "id")
        try values.encodeIfPresent(commandTypeDisplay, forKey: "command_type_display")
        try values.encodeIfPresent(lastCommandResultDisplay, forKey: "last_command_result_display")
        try values.encodeIfPresent(timerTypeDisplay, forKey: "timer_type_display")
        try values.encodeIfPresent(lastCommandExecution, forKey: "last_command_execution")
        try values.encodeIfPresent(isEnabled, forKey: "enabled")
        try values.encode(name, forKey: "name")
        try values.encodeIfPresent(timerType, forKey: "timer_type")
        try values.encodeIfPresent(commandType, forKey: "command_type")
        try values.encodeIfPresent(lastCommandResult, forKey: "last_command_result")
        try values.encodeIfPresent(isWeekdayMon, forKey: "weekday_mon")
        try values.encodeIfPresent(isWeekdayTue, forKey: "weekday_tue")
        try values.encodeIfPresent(isWeekdayWed, forKey: "weekday_wed")
        try values.encodeIfPresent(isWeekdayThu, forKey: "weekday_thu")
        try values.encodeIfPresent(isWeekdayFri, forKey: "weekday_fri")
        try values.encodeIfPresent(isWeekdaySat, forKey: "weekday_sat")
        try values.encodeIfPresent(isWeekdaySun, forKey: "weekday_sun")
        try values.encode(time, forKey: "time")
        try values.encodeIfPresent(date, forKey: "date")
    }
}
