// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct CommandResponse: Codable {
    public var message: String
    public var car: Car

    public init(message: String, car: Car) {
        self.message = message
        self.car = car
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.message = try values.decode(String.self, forKey: "message")
        self.car = try values.decode(Car.self, forKey: "car")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(message, forKey: "message")
        try values.encode(car, forKey: "car")
    }
}
