// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct EVInfo: Codable {
    public var id: Int?
    public var lastUpdated: Date?
    public var rangeAcon: Int?
    public var rangeAcoff: Int?
    /// Plugged in
    public var isPluggedIn: Bool?
    /// Charging
    public var isCharging: Bool?
    /// Charge finish
    public var isChargeFinish: Bool?
    /// Quick charging
    public var isQuickCharging: Bool?
    /// Ac status
    public var isAcStatus: Bool?
    public var chargeBars: Int?
    /// Car running
    public var isCarRunning: Bool?
    public var carGear: Int?
    /// Eco mode
    public var isEcoMode: Bool?
    public var soh: Int?
    public var soc: Double?
    public var socDisplay: Double?
    public var whContent: Double?
    public var capBars: Int?
    public var gids: Int?
    public var counter: Int?
    public var maxGids: Int?
    public var fullChgTime: Int?
    public var limitChgTime: Int?
    public var obc6kw: Int?
    public var param21: Int?
    public var cabinTemp: Double?
    /// Force soc display
    public var isForceSocDisplay: Bool?
    /// Obc 6kw avail
    public var isObc6kwAvail: Bool?
    /// Batt heater avail
    public var isBattHeaterAvail: Bool?
    /// Batt heater status
    public var isBattHeaterStatus: Bool?

    public init(id: Int? = nil, lastUpdated: Date? = nil, rangeAcon: Int? = nil, rangeAcoff: Int? = nil, isPluggedIn: Bool? = nil, isCharging: Bool? = nil, isChargeFinish: Bool? = nil, isQuickCharging: Bool? = nil, isAcStatus: Bool? = nil, chargeBars: Int? = nil, isCarRunning: Bool? = nil, carGear: Int? = nil, isEcoMode: Bool? = nil, soh: Int? = nil, soc: Double? = nil, socDisplay: Double? = nil, whContent: Double? = nil, capBars: Int? = nil, gids: Int? = nil, counter: Int? = nil, maxGids: Int? = nil, fullChgTime: Int? = nil, limitChgTime: Int? = nil, obc6kw: Int? = nil, param21: Int? = nil, cabinTemp: Double? = nil, isForceSocDisplay: Bool? = nil, isObc6kwAvail: Bool? = nil, isBattHeaterAvail: Bool? = nil, isBattHeaterStatus: Bool? = nil) {
        self.id = id
        self.lastUpdated = lastUpdated
        self.rangeAcon = rangeAcon
        self.rangeAcoff = rangeAcoff
        self.isPluggedIn = isPluggedIn
        self.isCharging = isCharging
        self.isChargeFinish = isChargeFinish
        self.isQuickCharging = isQuickCharging
        self.isAcStatus = isAcStatus
        self.chargeBars = chargeBars
        self.isCarRunning = isCarRunning
        self.carGear = carGear
        self.isEcoMode = isEcoMode
        self.soh = soh
        self.soc = soc
        self.socDisplay = socDisplay
        self.whContent = whContent
        self.capBars = capBars
        self.gids = gids
        self.counter = counter
        self.maxGids = maxGids
        self.fullChgTime = fullChgTime
        self.limitChgTime = limitChgTime
        self.obc6kw = obc6kw
        self.param21 = param21
        self.cabinTemp = cabinTemp
        self.isForceSocDisplay = isForceSocDisplay
        self.isObc6kwAvail = isObc6kwAvail
        self.isBattHeaterAvail = isBattHeaterAvail
        self.isBattHeaterStatus = isBattHeaterStatus
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decodeIfPresent(Int.self, forKey: "id")
        self.lastUpdated = try values.decodeIfPresent(Date.self, forKey: "last_updated")
        self.rangeAcon = try values.decodeIfPresent(Int.self, forKey: "range_acon")
        self.rangeAcoff = try values.decodeIfPresent(Int.self, forKey: "range_acoff")
        self.isPluggedIn = try values.decodeIfPresent(Bool.self, forKey: "plugged_in")
        self.isCharging = try values.decodeIfPresent(Bool.self, forKey: "charging")
        self.isChargeFinish = try values.decodeIfPresent(Bool.self, forKey: "charge_finish")
        self.isQuickCharging = try values.decodeIfPresent(Bool.self, forKey: "quick_charging")
        self.isAcStatus = try values.decodeIfPresent(Bool.self, forKey: "ac_status")
        self.chargeBars = try values.decodeIfPresent(Int.self, forKey: "charge_bars")
        self.isCarRunning = try values.decodeIfPresent(Bool.self, forKey: "car_running")
        self.carGear = try values.decodeIfPresent(Int.self, forKey: "car_gear")
        self.isEcoMode = try values.decodeIfPresent(Bool.self, forKey: "eco_mode")
        self.soh = try values.decodeIfPresent(Int.self, forKey: "soh")
        self.soc = try values.decodeIfPresent(Double.self, forKey: "soc")
        self.socDisplay = try values.decodeIfPresent(Double.self, forKey: "soc_display")
        self.whContent = try values.decodeIfPresent(Double.self, forKey: "wh_content")
        self.capBars = try values.decodeIfPresent(Int.self, forKey: "cap_bars")
        self.gids = try values.decodeIfPresent(Int.self, forKey: "gids")
        self.counter = try values.decodeIfPresent(Int.self, forKey: "counter")
        self.maxGids = try values.decodeIfPresent(Int.self, forKey: "max_gids")
        self.fullChgTime = try values.decodeIfPresent(Int.self, forKey: "full_chg_time")
        self.limitChgTime = try values.decodeIfPresent(Int.self, forKey: "limit_chg_time")
        self.obc6kw = try values.decodeIfPresent(Int.self, forKey: "obc_6kw")
        self.param21 = try values.decodeIfPresent(Int.self, forKey: "param21")
        self.cabinTemp = try values.decodeIfPresent(Double.self, forKey: "cabin_temp")
        self.isForceSocDisplay = try values.decodeIfPresent(Bool.self, forKey: "force_soc_display")
        self.isObc6kwAvail = try values.decodeIfPresent(Bool.self, forKey: "obc_6kw_avail")
        self.isBattHeaterAvail = try values.decodeIfPresent(Bool.self, forKey: "batt_heater_avail")
        self.isBattHeaterStatus = try values.decodeIfPresent(Bool.self, forKey: "batt_heater_status")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(id, forKey: "id")
        try values.encodeIfPresent(lastUpdated, forKey: "last_updated")
        try values.encodeIfPresent(rangeAcon, forKey: "range_acon")
        try values.encodeIfPresent(rangeAcoff, forKey: "range_acoff")
        try values.encodeIfPresent(isPluggedIn, forKey: "plugged_in")
        try values.encodeIfPresent(isCharging, forKey: "charging")
        try values.encodeIfPresent(isChargeFinish, forKey: "charge_finish")
        try values.encodeIfPresent(isQuickCharging, forKey: "quick_charging")
        try values.encodeIfPresent(isAcStatus, forKey: "ac_status")
        try values.encodeIfPresent(chargeBars, forKey: "charge_bars")
        try values.encodeIfPresent(isCarRunning, forKey: "car_running")
        try values.encodeIfPresent(carGear, forKey: "car_gear")
        try values.encodeIfPresent(isEcoMode, forKey: "eco_mode")
        try values.encodeIfPresent(soh, forKey: "soh")
        try values.encodeIfPresent(soc, forKey: "soc")
        try values.encodeIfPresent(socDisplay, forKey: "soc_display")
        try values.encodeIfPresent(whContent, forKey: "wh_content")
        try values.encodeIfPresent(capBars, forKey: "cap_bars")
        try values.encodeIfPresent(gids, forKey: "gids")
        try values.encodeIfPresent(counter, forKey: "counter")
        try values.encodeIfPresent(maxGids, forKey: "max_gids")
        try values.encodeIfPresent(fullChgTime, forKey: "full_chg_time")
        try values.encodeIfPresent(limitChgTime, forKey: "limit_chg_time")
        try values.encodeIfPresent(obc6kw, forKey: "obc_6kw")
        try values.encodeIfPresent(param21, forKey: "param21")
        try values.encodeIfPresent(cabinTemp, forKey: "cabin_temp")
        try values.encodeIfPresent(isForceSocDisplay, forKey: "force_soc_display")
        try values.encodeIfPresent(isObc6kwAvail, forKey: "obc_6kw_avail")
        try values.encodeIfPresent(isBattHeaterAvail, forKey: "batt_heater_avail")
        try values.encodeIfPresent(isBattHeaterStatus, forKey: "batt_heater_status")
    }
}
