// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct EVInfoUpdating: Codable {
    /// Force soc display
    public var isForceSocDisplay: Bool?

    public init(isForceSocDisplay: Bool? = nil) {
        self.isForceSocDisplay = isForceSocDisplay
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.isForceSocDisplay = try values.decodeIfPresent(Bool.self, forKey: "force_soc_display")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(isForceSocDisplay, forKey: "force_soc_display")
    }
}
