// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct JWTTokenLogin: Codable {
    public var refresh: String
    public var access: String?
    public var userID: Int?
    public var username: String?

    public init(refresh: String, access: String? = nil, userID: Int? = nil, username: String? = nil) {
        self.refresh = refresh
        self.access = access
        self.userID = userID
        self.username = username
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.refresh = try values.decode(String.self, forKey: "refresh")
        self.access = try values.decodeIfPresent(String.self, forKey: "access")
        self.userID = try values.decodeIfPresent(Int.self, forKey: "user_id")
        self.username = try values.decodeIfPresent(String.self, forKey: "username")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(refresh, forKey: "refresh")
        try values.encodeIfPresent(access, forKey: "access")
        try values.encodeIfPresent(userID, forKey: "user_id")
        try values.encodeIfPresent(username, forKey: "username")
    }
}
