// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct JWTTokenObtainPair: Codable {
    public var otpCode: String?
    public var deviceType: String?
    public var deviceOs: String?
    public var appVersion: String?
    public var pushNotificationKey: String?
    public var username: String
    public var password: String

    public init(otpCode: String? = nil, deviceType: String? = nil, deviceOs: String? = nil, appVersion: String? = nil, pushNotificationKey: String? = nil, username: String, password: String) {
        self.otpCode = otpCode
        self.deviceType = deviceType
        self.deviceOs = deviceOs
        self.appVersion = appVersion
        self.pushNotificationKey = pushNotificationKey
        self.username = username
        self.password = password
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.otpCode = try values.decodeIfPresent(String.self, forKey: "otp_code")
        self.deviceType = try values.decodeIfPresent(String.self, forKey: "device_type")
        self.deviceOs = try values.decodeIfPresent(String.self, forKey: "device_os")
        self.appVersion = try values.decodeIfPresent(String.self, forKey: "app_version")
        self.pushNotificationKey = try values.decodeIfPresent(String.self, forKey: "push_notification_key")
        self.username = try values.decode(String.self, forKey: "username")
        self.password = try values.decode(String.self, forKey: "password")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(otpCode, forKey: "otp_code")
        try values.encodeIfPresent(deviceType, forKey: "device_type")
        try values.encodeIfPresent(deviceOs, forKey: "device_os")
        try values.encodeIfPresent(appVersion, forKey: "app_version")
        try values.encodeIfPresent(pushNotificationKey, forKey: "push_notification_key")
        try values.encode(username, forKey: "username")
        try values.encode(password, forKey: "password")
    }
}
