// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct LocationInfo: Codable, Equatable {
    public var id: Int?
    public var lastUpdated: Date?
    public var lat: String?
    public var lon: String?
    /// Home
    public var isHome: Bool?

    public init(id: Int? = nil, lastUpdated: Date? = nil, lat: String? = nil, lon: String? = nil, isHome: Bool? = nil) {
        self.id = id
        self.lastUpdated = lastUpdated
        self.lat = lat
        self.lon = lon
        self.isHome = isHome
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decodeIfPresent(Int.self, forKey: "id")
        self.lastUpdated = try values.decodeIfPresent(Date.self, forKey: "last_updated")
        self.lat = try values.decodeIfPresent(String.self, forKey: "lat")
        self.lon = try values.decodeIfPresent(String.self, forKey: "lon")
        self.isHome = try values.decodeIfPresent(Bool.self, forKey: "home")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(id, forKey: "id")
        try values.encodeIfPresent(lastUpdated, forKey: "last_updated")
        try values.encodeIfPresent(lat, forKey: "lat")
        try values.encodeIfPresent(lon, forKey: "lon")
        try values.encodeIfPresent(isHome, forKey: "home")
    }
}
