// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct MapLinkResolvedLocation: Codable {
    public var lat: Double
    public var lon: Double
    public var name: String
    public var address: String

    public init(lat: Double, lon: Double, name: String, address: String) {
        self.lat = lat
        self.lon = lon
        self.name = name
        self.address = address
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.lat = try values.decode(Double.self, forKey: "lat")
        self.lon = try values.decode(Double.self, forKey: "lon")
        self.name = try values.decode(String.self, forKey: "name")
        self.address = try values.decode(String.self, forKey: "address")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(lat, forKey: "lat")
        try values.encode(lon, forKey: "lon")
        try values.encode(name, forKey: "name")
        try values.encode(address, forKey: "address")
    }
}
