// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct MapLinkResolverResponse: Codable {
    /// Status
    public var isStatus: Bool
    public var cause: String?
    public var location: MapLinkResolvedLocation?

    public init(isStatus: Bool, cause: String? = nil, location: MapLinkResolvedLocation? = nil) {
        self.isStatus = isStatus
        self.cause = cause
        self.location = location
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.isStatus = try values.decode(Bool.self, forKey: "status")
        self.cause = try values.decodeIfPresent(String.self, forKey: "cause")
        self.location = try values.decodeIfPresent(MapLinkResolvedLocation.self, forKey: "location")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(isStatus, forKey: "status")
        try values.encodeIfPresent(cause, forKey: "cause")
        try values.encodeIfPresent(location, forKey: "location")
    }
}
