// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct PinChange: Codable {
    public var otpCode: String?
    public var oldPin: String?
    public var newPin: String
    public var newPinConfirm: String

    public init(otpCode: String? = nil, oldPin: String? = nil, newPin: String, newPinConfirm: String) {
        self.otpCode = otpCode
        self.oldPin = oldPin
        self.newPin = newPin
        self.newPinConfirm = newPinConfirm
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.otpCode = try values.decodeIfPresent(String.self, forKey: "otp_code")
        self.oldPin = try values.decodeIfPresent(String.self, forKey: "old_pin")
        self.newPin = try values.decode(String.self, forKey: "new_pin")
        self.newPinConfirm = try values.decode(String.self, forKey: "new_pin_confirm")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(otpCode, forKey: "otp_code")
        try values.encodeIfPresent(oldPin, forKey: "old_pin")
        try values.encode(newPin, forKey: "new_pin")
        try values.encode(newPinConfirm, forKey: "new_pin_confirm")
    }
}
