// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct RestAPIError: Codable {
    public var detail: String?
    public var error: String?

    public init(detail: String? = nil, error: String? = nil) {
        self.detail = detail
        self.error = error
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.detail = try values.decodeIfPresent(String.self, forKey: "detail")
        self.error = try values.decodeIfPresent(String.self, forKey: "error")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(detail, forKey: "detail")
        try values.encodeIfPresent(error, forKey: "error")
    }
}
