// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct RoutePlan: Codable {
    public var id: Int?
    public var name: String
    public var createdAt: Date?
    public var startName: String
    public var startLat: String
    public var startLon: String
    public var finishName: String
    public var finishLat: String
    public var finishLon: String
    public var point1Name: String?
    public var point1Lat: String?
    public var point1Lon: String?
    public var point2Name: String?
    public var point2Lat: String?
    public var point2Lon: String?
    public var point3Name: String?
    public var point3Lat: String?
    public var point3Lon: String?
    public var point4Name: String?
    public var point4Lat: String?
    public var point4Lon: String?
    public var point5Name: String?
    public var point5Lat: String?
    public var point5Lon: String?

    public init(id: Int? = nil, name: String, createdAt: Date? = nil, startName: String, startLat: String, startLon: String, finishName: String, finishLat: String, finishLon: String, point1Name: String? = nil, point1Lat: String? = nil, point1Lon: String? = nil, point2Name: String? = nil, point2Lat: String? = nil, point2Lon: String? = nil, point3Name: String? = nil, point3Lat: String? = nil, point3Lon: String? = nil, point4Name: String? = nil, point4Lat: String? = nil, point4Lon: String? = nil, point5Name: String? = nil, point5Lat: String? = nil, point5Lon: String? = nil) {
        self.id = id
        self.name = name
        self.createdAt = createdAt
        self.startName = startName
        self.startLat = startLat
        self.startLon = startLon
        self.finishName = finishName
        self.finishLat = finishLat
        self.finishLon = finishLon
        self.point1Name = point1Name
        self.point1Lat = point1Lat
        self.point1Lon = point1Lon
        self.point2Name = point2Name
        self.point2Lat = point2Lat
        self.point2Lon = point2Lon
        self.point3Name = point3Name
        self.point3Lat = point3Lat
        self.point3Lon = point3Lon
        self.point4Name = point4Name
        self.point4Lat = point4Lat
        self.point4Lon = point4Lon
        self.point5Name = point5Name
        self.point5Lat = point5Lat
        self.point5Lon = point5Lon
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decodeIfPresent(Int.self, forKey: "id")
        self.name = try values.decode(String.self, forKey: "name")
        self.createdAt = try values.decodeIfPresent(Date.self, forKey: "created_at")
        self.startName = try values.decode(String.self, forKey: "start_name")
        self.startLat = try values.decode(String.self, forKey: "start_lat")
        self.startLon = try values.decode(String.self, forKey: "start_lon")
        self.finishName = try values.decode(String.self, forKey: "finish_name")
        self.finishLat = try values.decode(String.self, forKey: "finish_lat")
        self.finishLon = try values.decode(String.self, forKey: "finish_lon")
        self.point1Name = try values.decodeIfPresent(String.self, forKey: "point1_name")
        self.point1Lat = try values.decodeIfPresent(String.self, forKey: "point1_lat")
        self.point1Lon = try values.decodeIfPresent(String.self, forKey: "point1_lon")
        self.point2Name = try values.decodeIfPresent(String.self, forKey: "point2_name")
        self.point2Lat = try values.decodeIfPresent(String.self, forKey: "point2_lat")
        self.point2Lon = try values.decodeIfPresent(String.self, forKey: "point2_lon")
        self.point3Name = try values.decodeIfPresent(String.self, forKey: "point3_name")
        self.point3Lat = try values.decodeIfPresent(String.self, forKey: "point3_lat")
        self.point3Lon = try values.decodeIfPresent(String.self, forKey: "point3_lon")
        self.point4Name = try values.decodeIfPresent(String.self, forKey: "point4_name")
        self.point4Lat = try values.decodeIfPresent(String.self, forKey: "point4_lat")
        self.point4Lon = try values.decodeIfPresent(String.self, forKey: "point4_lon")
        self.point5Name = try values.decodeIfPresent(String.self, forKey: "point5_name")
        self.point5Lat = try values.decodeIfPresent(String.self, forKey: "point5_lat")
        self.point5Lon = try values.decodeIfPresent(String.self, forKey: "point5_lon")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(id, forKey: "id")
        try values.encode(name, forKey: "name")
        try values.encodeIfPresent(createdAt, forKey: "created_at")
        try values.encode(startName, forKey: "start_name")
        try values.encode(startLat, forKey: "start_lat")
        try values.encode(startLon, forKey: "start_lon")
        try values.encode(finishName, forKey: "finish_name")
        try values.encode(finishLat, forKey: "finish_lat")
        try values.encode(finishLon, forKey: "finish_lon")
        try values.encodeIfPresent(point1Name, forKey: "point1_name")
        try values.encodeIfPresent(point1Lat, forKey: "point1_lat")
        try values.encodeIfPresent(point1Lon, forKey: "point1_lon")
        try values.encodeIfPresent(point2Name, forKey: "point2_name")
        try values.encodeIfPresent(point2Lat, forKey: "point2_lat")
        try values.encodeIfPresent(point2Lon, forKey: "point2_lon")
        try values.encodeIfPresent(point3Name, forKey: "point3_name")
        try values.encodeIfPresent(point3Lat, forKey: "point3_lat")
        try values.encodeIfPresent(point3Lon, forKey: "point3_lon")
        try values.encodeIfPresent(point4Name, forKey: "point4_name")
        try values.encodeIfPresent(point4Lat, forKey: "point4_lat")
        try values.encodeIfPresent(point4Lon, forKey: "point4_lon")
        try values.encodeIfPresent(point5Name, forKey: "point5_name")
        try values.encodeIfPresent(point5Lat, forKey: "point5_lat")
        try values.encodeIfPresent(point5Lon, forKey: "point5_lon")
    }
}
