// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct SendToCarLocation: Codable {
    public var id: Int?
    public var lat: String
    public var lon: String
    public var name: String
    public var createdAt: Date?

    public init(id: Int? = nil, lat: String, lon: String, name: String, createdAt: Date? = nil) {
        self.id = id
        self.lat = lat
        self.lon = lon
        self.name = name
        self.createdAt = createdAt
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decodeIfPresent(Int.self, forKey: "id")
        self.lat = try values.decode(String.self, forKey: "lat")
        self.lon = try values.decode(String.self, forKey: "lon")
        self.name = try values.decode(String.self, forKey: "name")
        self.createdAt = try values.decodeIfPresent(Date.self, forKey: "created_at")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(id, forKey: "id")
        try values.encode(lat, forKey: "lat")
        try values.encode(lon, forKey: "lon")
        try values.encode(name, forKey: "name")
        try values.encodeIfPresent(createdAt, forKey: "created_at")
    }
}
