// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct TCUConfiguration: Codable {
    public var id: Int?
    public var lastUpdated: Date?
    public var dialCode: String?
    public var apn: String?
    public var apnUser: String?
    public var apnPassword: String?
    public var dns1: String?
    public var dns2: String?
    public var serverURL: String?
    public var proxyURL: String?
    public var connectionType: String?
    public var ficosaConfig: [String: AnyJSON]?

    public init(id: Int? = nil, lastUpdated: Date? = nil, dialCode: String? = nil, apn: String? = nil, apnUser: String? = nil, apnPassword: String? = nil, dns1: String? = nil, dns2: String? = nil, serverURL: String? = nil, proxyURL: String? = nil, connectionType: String? = nil, ficosaConfig: [String: AnyJSON]? = nil) {
        self.id = id
        self.lastUpdated = lastUpdated
        self.dialCode = dialCode
        self.apn = apn
        self.apnUser = apnUser
        self.apnPassword = apnPassword
        self.dns1 = dns1
        self.dns2 = dns2
        self.serverURL = serverURL
        self.proxyURL = proxyURL
        self.connectionType = connectionType
        self.ficosaConfig = ficosaConfig
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decodeIfPresent(Int.self, forKey: "id")
        self.lastUpdated = try values.decodeIfPresent(Date.self, forKey: "last_updated")
        self.dialCode = try values.decodeIfPresent(String.self, forKey: "dial_code")
        self.apn = try values.decodeIfPresent(String.self, forKey: "apn")
        self.apnUser = try values.decodeIfPresent(String.self, forKey: "apn_user")
        self.apnPassword = try values.decodeIfPresent(String.self, forKey: "apn_password")
        self.dns1 = try values.decodeIfPresent(String.self, forKey: "dns1")
        self.dns2 = try values.decodeIfPresent(String.self, forKey: "dns2")
        self.serverURL = try values.decodeIfPresent(String.self, forKey: "server_url")
        self.proxyURL = try values.decodeIfPresent(String.self, forKey: "proxy_url")
        self.connectionType = try values.decodeIfPresent(String.self, forKey: "connection_type")
        self.ficosaConfig = try values.decodeIfPresent([String: AnyJSON].self, forKey: "ficosa_config")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(id, forKey: "id")
        try values.encodeIfPresent(lastUpdated, forKey: "last_updated")
        try values.encodeIfPresent(dialCode, forKey: "dial_code")
        try values.encodeIfPresent(apn, forKey: "apn")
        try values.encodeIfPresent(apnUser, forKey: "apn_user")
        try values.encodeIfPresent(apnPassword, forKey: "apn_password")
        try values.encodeIfPresent(dns1, forKey: "dns1")
        try values.encodeIfPresent(dns2, forKey: "dns2")
        try values.encodeIfPresent(serverURL, forKey: "server_url")
        try values.encodeIfPresent(proxyURL, forKey: "proxy_url")
        try values.encodeIfPresent(connectionType, forKey: "connection_type")
        try values.encodeIfPresent(ficosaConfig, forKey: "ficosa_config")
    }
}
