// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct TokenBlacklist: Codable {
    public var refresh: String

    public init(refresh: String) {
        self.refresh = refresh
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.refresh = try values.decode(String.self, forKey: "refresh")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(refresh, forKey: "refresh")
    }
}
