// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct TokenMetadataUpdate: Codable {
    public var refresh: String
    public var deviceType: String?
    public var deviceOs: String?
    public var appVersion: String?
    public var pushNotificationKey: String?

    public init(refresh: String, deviceType: String? = nil, deviceOs: String? = nil, appVersion: String? = nil, pushNotificationKey: String? = nil) {
        self.refresh = refresh
        self.deviceType = deviceType
        self.deviceOs = deviceOs
        self.appVersion = appVersion
        self.pushNotificationKey = pushNotificationKey
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.refresh = try values.decode(String.self, forKey: "refresh")
        self.deviceType = try values.decodeIfPresent(String.self, forKey: "device_type")
        self.deviceOs = try values.decodeIfPresent(String.self, forKey: "device_os")
        self.appVersion = try values.decodeIfPresent(String.self, forKey: "app_version")
        self.pushNotificationKey = try values.decodeIfPresent(String.self, forKey: "push_notification_key")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(refresh, forKey: "refresh")
        try values.encodeIfPresent(deviceType, forKey: "device_type")
        try values.encodeIfPresent(deviceOs, forKey: "device_os")
        try values.encodeIfPresent(appVersion, forKey: "app_version")
        try values.encodeIfPresent(pushNotificationKey, forKey: "push_notification_key")
    }
}
