// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct TokenRefresh: Codable {
    public var refresh: String
    public var access: String?

    public init(refresh: String, access: String? = nil) {
        self.refresh = refresh
        self.access = access
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.refresh = try values.decode(String.self, forKey: "refresh")
        self.access = try values.decodeIfPresent(String.self, forKey: "access")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(refresh, forKey: "refresh")
        try values.encodeIfPresent(access, forKey: "access")
    }
}
