// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct TokenMetadata: Codable {
    public var deviceType: String?
    public var deviceOs: String?
    public var appVersion: String?
    public var pushNotificationKey: String?
    public var userAgent: String?
    public var lastUsedAt: Date?

    public init(deviceType: String? = nil, deviceOs: String? = nil, appVersion: String? = nil, pushNotificationKey: String? = nil, userAgent: String? = nil, lastUsedAt: Date? = nil) {
        self.deviceType = deviceType
        self.deviceOs = deviceOs
        self.appVersion = appVersion
        self.pushNotificationKey = pushNotificationKey
        self.userAgent = userAgent
        self.lastUsedAt = lastUsedAt
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.deviceType = try values.decodeIfPresent(String.self, forKey: "device_type")
        self.deviceOs = try values.decodeIfPresent(String.self, forKey: "device_os")
        self.appVersion = try values.decodeIfPresent(String.self, forKey: "app_version")
        self.pushNotificationKey = try values.decodeIfPresent(String.self, forKey: "push_notification_key")
        self.userAgent = try values.decodeIfPresent(String.self, forKey: "user_agent")
        self.lastUsedAt = try values.decodeIfPresent(Date.self, forKey: "last_used_at")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(deviceType, forKey: "device_type")
        try values.encodeIfPresent(deviceOs, forKey: "device_os")
        try values.encodeIfPresent(appVersion, forKey: "app_version")
        try values.encodeIfPresent(pushNotificationKey, forKey: "push_notification_key")
        try values.encodeIfPresent(userAgent, forKey: "user_agent")
        try values.encodeIfPresent(lastUsedAt, forKey: "last_used_at")
    }
}
