// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct VehicleHealthInfo: Codable {
    public var id: Int?
    public var lastUpdated: Date?
    public var dtcTimestamp: Date?
    public var dtcShort: [DTC_Code]?
    public var dtcLong: [DTC_Code]?
    /// Tpms light
    public var isTpmsLight: Bool?
    public var tpmsFr: Int?
    public var tpmsFl: Int?
    public var tpmsRr: Int?
    public var tpmsRl: Int?
    /// Maintenance alert
    public var isMaintenanceAlert: Bool?
    public var mileage: Double?

    public init(id: Int? = nil, lastUpdated: Date? = nil, dtcTimestamp: Date? = nil, dtcShort: [DTC_Code]? = nil, dtcLong: [DTC_Code]? = nil, isTpmsLight: Bool? = nil, tpmsFr: Int? = nil, tpmsFl: Int? = nil, tpmsRr: Int? = nil, tpmsRl: Int? = nil, isMaintenanceAlert: Bool? = nil, mileage: Double? = nil) {
        self.id = id
        self.lastUpdated = lastUpdated
        self.dtcTimestamp = dtcTimestamp
        self.dtcShort = dtcShort
        self.dtcLong = dtcLong
        self.isTpmsLight = isTpmsLight
        self.tpmsFr = tpmsFr
        self.tpmsFl = tpmsFl
        self.tpmsRr = tpmsRr
        self.tpmsRl = tpmsRl
        self.isMaintenanceAlert = isMaintenanceAlert
        self.mileage = mileage
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decodeIfPresent(Int.self, forKey: "id")
        self.lastUpdated = try values.decodeIfPresent(Date.self, forKey: "last_updated")
        self.dtcTimestamp = try values.decodeIfPresent(Date.self, forKey: "dtc_timestamp")
        self.dtcShort = try values.decodeIfPresent([DTC_Code].self, forKey: "dtc_short")
        self.dtcLong = try values.decodeIfPresent([DTC_Code].self, forKey: "dtc_long")
        self.isTpmsLight = try values.decodeIfPresent(Bool.self, forKey: "tpms_light")
        self.tpmsFr = try values.decodeIfPresent(Int.self, forKey: "tpms_fr")
        self.tpmsFl = try values.decodeIfPresent(Int.self, forKey: "tpms_fl")
        self.tpmsRr = try values.decodeIfPresent(Int.self, forKey: "tpms_rr")
        self.tpmsRl = try values.decodeIfPresent(Int.self, forKey: "tpms_rl")
        self.isMaintenanceAlert = try values.decodeIfPresent(Bool.self, forKey: "maintenance_alert")
        self.mileage = try values.decodeIfPresent(Double.self, forKey: "mileage")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(id, forKey: "id")
        try values.encodeIfPresent(lastUpdated, forKey: "last_updated")
        try values.encodeIfPresent(dtcTimestamp, forKey: "dtc_timestamp")
        try values.encodeIfPresent(dtcShort, forKey: "dtc_short")
        try values.encodeIfPresent(dtcLong, forKey: "dtc_long")
        try values.encodeIfPresent(isTpmsLight, forKey: "tpms_light")
        try values.encodeIfPresent(tpmsFr, forKey: "tpms_fr")
        try values.encodeIfPresent(tpmsFl, forKey: "tpms_fl")
        try values.encodeIfPresent(tpmsRr, forKey: "tpms_rr")
        try values.encodeIfPresent(tpmsRl, forKey: "tpms_rl")
        try values.encodeIfPresent(isMaintenanceAlert, forKey: "maintenance_alert")
        try values.encodeIfPresent(mileage, forKey: "mileage")
    }
}
