// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths.API.Maplink {
    public var resolve: Resolve {
        Resolve(path: path + "/resolve")
    }

    public struct Resolve {
        /// Path: `/api/maplink/resolve`
        public let path: String

        /// Resolve maps link from Google or Apple into location
        public func post(_ body: RestAPI.MapLinkResolverInput) -> Request<RestAPI.MapLinkResolverResponse> {
            Request(path: path, method: "POST", body: body, id: "api_maplink_resolve_create")
        }
    }
}
