// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths.API.Token {
    public var update: Update {
        Update(path: path + "/update")
    }

    public struct Update {
        /// Path: `/api/token/update`
        public let path: String

        /// Update token metadata
        public func post(_ body: RestAPI.TokenMetadataUpdate) -> Request<RestAPI.TokenMetadata> {
            Request(path: path, method: "POST", body: body, id: "api_token_update_create")
        }
    }
}
