// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths.API.Car.WithVin.Timers {
    public func id(_ id: String) -> WithID {
        WithID(path: "\(path)\(id)")
    }

    public struct WithID {
        /// Path: `/api/car/{vin}/timers/{id}`
        public let path: String

        public var get: Request<RestAPI.CommandTimerSetting> {
            Request(path: path, method: "GET", id: "api_car_timers_read")
        }

        public func put(_ body: RestAPI.CommandTimerSetting) -> Request<RestAPI.CommandTimerSetting> {
            Request(path: path, method: "PUT", body: body, id: "api_car_timers_update")
        }

        public func patch(_ body: RestAPI.CommandTimerSetting) -> Request<RestAPI.CommandTimerSetting> {
            Request(path: path, method: "PATCH", body: body, id: "api_car_timers_partial_update")
        }

        public var delete: Request<Void> {
            Request(path: path, method: "DELETE", id: "api_car_timers_delete")
        }
    }
}
