// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths.Account {
    public var detail: Detail {
        Detail(path: path + "/detail/")
    }

    public struct Detail {
        /// Path: `/account/detail`
        public let path: String

        /// Get basic account details
        public var get: Request<RestAPI.AccountDetail> {
            Request(path: path, method: "GET", id: "account_detail_list")
        }
    }
}
