// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths.Account {
    public var resetAPIKey: ResetAPIKey {
        ResetAPIKey(path: path + "/reset-api-key/")
    }

    public struct ResetAPIKey {
        /// Path: `/account/reset-api-key`
        public let path: String

        /// Reset API-key. ONLY accessible from web portal!
        public var post: Request<Void> {
            Request(path: path, method: "POST", id: "account_reset-api-key_create")
        }
    }
}
