// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths {
    public static var api: API {
        API(path: "/api")
    }

    public struct API {
        /// Path: `/api`
        public let path: String
    }
}
