// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths.Account {
    public var pin: Pin {
        Pin(path: path + "/pin/")
    }

    public struct Pin {
        /// Path: `/account/pin`
        public let path: String

        /// Change command PIN, requires OTP code if 2FA is enabled, or old pin if disabled
        public func post(_ body: RestAPI.PinChange) -> Request<Void> {
            Request(path: path, method: "POST", body: body, id: "account_pin_create")
        }
    }
}
