// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths.API.Probe.Location {
    public func vin(_ vin: String) -> WithVin {
        WithVin(path: "\(path)/\(vin)")
    }

    public struct WithVin {
        /// Path: `/api/probe/location/{vin}`
        public let path: String

        public var get: Request<Void> {
            Request(path: path, method: "GET", id: "api_probe_location_read")
        }
    }
}
