// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths.API {
    public var probe: Probe {
        Probe(path: path + "/probe")
    }

    public struct Probe {
        /// Path: `/api/probe`
        public let path: String
    }
}
