// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths.API {
    public var maplink: Maplink {
        Maplink(path: path + "/maplink")
    }

    public struct Maplink {
        /// Path: `/api/maplink`
        public let path: String
    }
}
