// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths.API {
    public var token: Token {
        Token(path: path + "/token")
    }

    public struct Token {
        /// Path: `/api/token`
        public let path: String
    }
}
