// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths.API.Car {
    public func vin(_ vin: String) -> WithVin {
        WithVin(path: "\(path)/\(vin)/")
    }

    public struct WithVin {
        /// Path: `/api/car/{vin}`
        public let path: String

        public var get: Request<RestAPI.Car> {
            Request(path: path, method: "GET", id: "api_car_read")
        }

        public func put(_ body: RestAPI.CarUpdating) -> Request<RestAPI.Car> {
            Request(path: path, method: "PUT", body: body, id: "api_car_update")
        }

        public func patch(_ body: RestAPI.CarUpdating) -> Request<RestAPI.Car> {
            Request(path: path, method: "PATCH", body: body, id: "api_car_partial_update")
        }

        public var delete: Request<Void> {
            Request(path: path, method: "DELETE", id: "api_car_delete")
        }
    }
}
