// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths.API.Probe {
    public var location: Location {
        Location(path: path + "/location")
    }

    public struct Location {
        /// Path: `/api/probe/location`
        public let path: String
    }
}
