// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths.API {
    public var command: Command {
        Command(path: path + "/command")
    }

    public struct Command {
        /// Path: `/api/command`
        public let path: String
    }
}
