// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths.API.Car.WithVin {
    public var timers: Timers {
        Timers(path: path + "timers/")
    }

    public struct Timers {
        /// Path: `/api/car/{vin}/timers`
        public let path: String

        public var get: Request<[RestAPI.CommandTimerSetting]> {
            Request(path: path, method: "GET", id: "api_car_timers_list")
        }

        public func post(_ body: RestAPI.CommandTimerSetting) -> Request<RestAPI.CommandTimerSetting> {
            Request(path: path, method: "POST", body: body, id: "api_car_timers_create")
        }
    }
}
