// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths.API.Token {
    public var refresh: Refresh {
        Refresh(path: path + "/refresh/")
    }

    public struct Refresh {
        /// Path: `/api/token/refresh`
        public let path: String

        /// Takes a refresh type JSON web token and returns an access type JSON web
        /// token if the refresh token is valid.
        public func post(_ body: RestAPI.TokenRefresh) -> Request<RestAPI.TokenRefresh> {
            Request(path: path, method: "POST", body: body, id: "api_token_refresh_create")
        }
    }
}
