// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths.API {
    public var car: Car {
        Car(path: path + "/car")
    }

    public struct Car {
        /// Path: `/api/car`
        public let path: String

        /// Retrieve a list of cars
        public var get: Request<[RestAPI.CarSerializerList]> {
            Request(path: path, method: "GET", id: "api_car_list")
        }
    }
}
