// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths.API.Token {
    public var obtain: Obtain {
        Obtain(path: path + "/obtain")
    }

    public struct Obtain {
        /// Path: `/api/token/obtain`
        public let path: String

        public func post(_ body: RestAPI.JWTTokenObtainPair) -> Request<RestAPI.JWTTokenLogin> {
            Request(path: path, method: "POST", body: body, id: "api_token_obtain_create")
        }
    }
}
