// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths.API.Command {
    public func vin(_ vin: String) -> WithVin {
        WithVin(path: "\(path)/\(vin)")
    }

    public struct WithVin {
        /// Path: `/api/command/{vin}`
        public let path: String

        /// Send a command to your vehicle
        public func post(_ body: PostRequest) -> Request<RestAPI.CommandResponse> {
            Request(path: path, method: "POST", body: body, id: "api_command_create")
        }

        public struct PostRequest: Encodable {
            public var commandType: Double
            public var commandPayload: [String: AnyJSON]?
            /// PIN code for command types [7, 8, 9, 10, 11, 12, 13, 14]
            public var commandPin: String?

            public init(commandType: Double, commandPayload: [String: AnyJSON]? = nil, commandPin: String? = nil) {
                self.commandType = commandType
                self.commandPayload = commandPayload
                self.commandPin = commandPin
            }

            public func encode(to encoder: Encoder) throws {
                var values = encoder.container(keyedBy: StringCodingKey.self)
                try values.encode(commandType, forKey: "command_type")
                try values.encodeIfPresent(commandPayload, forKey: "command_payload")
                try values.encodeIfPresent(commandPin, forKey: "command_pin")
            }
        }
    }
}
