// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths.API.Alerts {
    public func vin(_ vin: String) -> WithVin {
        WithVin(path: "\(path)/\(vin)/")
    }

    public struct WithVin {
        /// Path: `/api/alerts/{vin}`
        public let path: String

        /// Retrieve a list of alerts for a vehicle
        public var get: Request<[RestAPI.AlertHistoryFull]> {
            Request(path: path, method: "GET", id: "api_alerts_read")
        }
    }
}
