// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths.API.Token {
    public var signout: Signout {
        Signout(path: path + "/signout/")
    }

    public struct Signout {
        /// Path: `/api/token/signout`
        public let path: String

        /// Sign out and invalidate tokens
        public func post(_ body: RestAPI.TokenBlacklist) -> Request<Void> {
            Request(path: path, method: "POST", body: body, id: "api_token_signout_create")
        }
    }
}
